### ISSUE TITLE
Sometimes format is null for the embedded image

### ISSUE THREAD

**Issue by ApurvGpt** [splitbee/react-notion#31]
Use this doc, the library breaks for the second blog

https://www.notion.so/5dbf519a81a14616ba35b62c196cd823

getting the following error

TypeError: Cannot read property 'block_width' of undefined
    at Block (C:\Users\apurv\source\mailmodo\next-blog\node_modules\react-notion\dist\react-notion.cjs.development.js:376:31)
    at processChild (C:\Users\apurv\source\mailmodo\next-blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3043:14)
    at resolve (C:\Users\apurv\source\mailmodo\next-blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (C:\Users\apurv\source\mailmodo\next-blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (C:\Users\apurv\source\mailmodo\next-blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3373:29)
    at renderToString (C:\Users\apurv\source\mailmodo\next-blog\node_modules\react-dom\cjs\react-dom-server.node.development.js:3988:27)
    at Object.renderPage (C:\Users\apurv\source\mailmodo\next-blog\node_modules\next\dist\next-server\server\render.js:50:851)
    at Function.getInitialProps (C:\Users\apurv\source\mailmodo\next-blog\.next\server\pages\_document.js:299:19)
    at loadGetInitialProps (C:\Users\apurv\source\mailmodo\next-blog\node_modules\next\dist\next-server\lib\utils.js:5:101)
    at renderToHTML (C:\Users\apurv\source\mailmodo\next-blog\node_modules\next\dist\next-server\server\render.js:50:1142)

**Comment by tobiaslins** [comment]
@ApurvGpt I just tried all 3 posts and all seem to work fine (except that the images are not available anymore)

Please reopen the issue with a notion-document that can reproduce this!
